name: Benchmark
on: [push]
jobs:
  bench1:
    runs-on: ubuntu-latest
    name: create vs build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Benchmark
      run: |
        ruby create-vs-build/bench-io.rb
        ruby create-vs-build/bench-on-memory.rb
  bench2:
    runs-on: ubuntu-latest
    name: belongs_to association
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Benchmark
      run: |
        ruby belongs_to-association/bench-on-memory.rb
        ruby belongs_to-association/bench-io.rb
  bench3:
    runs-on: ubuntu-latest
    name: has_many association
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Benchmark
      run: |
        ruby has_many-association/bench-on-memory.rb
        ruby has_many-association/bench-io.rb
  bench4:
    runs-on: ubuntu-latest
    name: always create association
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Benchmark
      run: |
        ruby always-create-association/bench-on-memory.rb
        ruby always-create-association/bench-io.rb
